// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKYNsNOS5mY7fb52Tc31aE6jF7sbvlXj0',
    appId: '1:833984237850:web:404319f3bc34fbc8a99ca3',
    messagingSenderId: '833984237850',
    projectId: 'ititask2',
    authDomain: 'ititask2.firebaseapp.com',
    storageBucket: 'ititask2.appspot.com',
    measurementId: 'G-R4DZD4S0E4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALOhW5KkO6c9njOj9Ftsp16RfbJ7Fywz4',
    appId: '1:833984237850:android:1e76f227db131d75a99ca3',
    messagingSenderId: '833984237850',
    projectId: 'ititask2',
    storageBucket: 'ititask2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYepddXHAzfZJRlRg9jR06vWOhM2GXnE4',
    appId: '1:833984237850:ios:7c63460aadc609f5a99ca3',
    messagingSenderId: '833984237850',
    projectId: 'ititask2',
    storageBucket: 'ititask2.appspot.com',
    iosClientId: '833984237850-kk0hde6hjfe5meoq51hh51td2fp53skc.apps.googleusercontent.com',
    iosBundleId: 'com.example.theproject',
  );
}
